import type { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ChatGroupLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode
}) {
  // const session = await getSession();
  return (
    // <SessionProvider session={session}>
    //     <Header />
    //     {children}
    // </SessionProvider>

      <>
        <Header />
        {children}
    </>
  )
}